// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Módulo de login
Essa é uma API de autenticação simples, criada com o intuido de apenas validar as credenciais dos usuários.


    Schemes:
      http
    Host: localhost
    BasePath: /api
    Version: 1.0.0
    Contact: Joel Felipe de Oliveira Gaya<joelfelipe94@gmail.com>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
