// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Essa é uma API de autenticação simples, criada com o intuido de apenas validar as credenciais dos usuários.",
    "title": "Módulo de login",
    "contact": {
      "name": "Joel Felipe de Oliveira Gaya",
      "email": "joelfelipe94@gmail.com"
    },
    "version": "1.0.0"
  },
  "basePath": "/api",
  "paths": {
    "/login": {
      "post": {
        "description": "Verifica se as credenciais dos usuários estão corretas.",
        "operationId": "login",
        "parameters": [
          {
            "description": "Credenciais",
            "name": "Credenciais",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Credenciais"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Sucesso"
          },
          "401": {
            "description": "Usuário não autorizado"
          },
          "default": {
            "description": "Erro inesperado",
            "schema": {
              "$ref": "#/definitions/Erro"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Credenciais": {
      "type": "object",
      "allOf": [
        {
          "required": [
            "usuario",
            "senha"
          ],
          "properties": {
            "senha": {
              "type": "string"
            },
            "usuario": {
              "type": "string"
            }
          }
        }
      ]
    },
    "Erro": {
      "type": "object",
      "properties": {
        "codigo": {
          "type": "integer",
          "format": "int"
        },
        "mensagem": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Essa é uma API de autenticação simples, criada com o intuido de apenas validar as credenciais dos usuários.",
    "title": "Módulo de login",
    "contact": {
      "name": "Joel Felipe de Oliveira Gaya",
      "email": "joelfelipe94@gmail.com"
    },
    "version": "1.0.0"
  },
  "basePath": "/api",
  "paths": {
    "/login": {
      "post": {
        "description": "Verifica se as credenciais dos usuários estão corretas.",
        "operationId": "login",
        "parameters": [
          {
            "description": "Credenciais",
            "name": "Credenciais",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Credenciais"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Sucesso"
          },
          "401": {
            "description": "Usuário não autorizado"
          },
          "default": {
            "description": "Erro inesperado",
            "schema": {
              "$ref": "#/definitions/Erro"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Credenciais": {
      "type": "object",
      "allOf": [
        {
          "required": [
            "usuario",
            "senha"
          ],
          "properties": {
            "senha": {
              "type": "string"
            },
            "usuario": {
              "type": "string"
            }
          }
        }
      ]
    },
    "Erro": {
      "type": "object",
      "properties": {
        "codigo": {
          "type": "integer",
          "format": "int"
        },
        "mensagem": {
          "type": "string"
        }
      }
    }
  }
}`))
}
