// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Erro erro
// swagger:model Erro
type Erro struct {

	// codigo
	// Required: true
	Codigo *int32 `json:"codigo"`

	// menssagem
	// Required: true
	Menssagem *string `json:"menssagem"`
}

// Validate validates this erro
func (m *Erro) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCodigo(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMenssagem(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Erro) validateCodigo(formats strfmt.Registry) error {

	if err := validate.Required("codigo", "body", m.Codigo); err != nil {
		return err
	}

	return nil
}

func (m *Erro) validateMenssagem(formats strfmt.Registry) error {

	if err := validate.Required("menssagem", "body", m.Menssagem); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Erro) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Erro) UnmarshalBinary(b []byte) error {
	var res Erro
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
