// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Erro erro
// swagger:model Erro
type Erro struct {

	// codigo
	Codigo int64 `json:"codigo,omitempty"`

	// mensagem
	Mensagem string `json:"mensagem,omitempty"`
}

// Validate validates this erro
func (m *Erro) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Erro) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Erro) UnmarshalBinary(b []byte) error {
	var res Erro
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
